name = "SingularIntegralEquations"
uuid = "e094c991-5a90-5477-8896-c1e4c9552a1a"
version = "0.5"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
ApproxFunBase = "fbd15aa5-315a-5a7d-a8a4-24992e37be05"
ApproxFunFourier = "59844689-9c9d-51bf-9583-5b794ec66d30"
ApproxFunOrthogonalPolynomials = "b70543e2-c0d9-56b8-a290-0d4d6d4de211"
ApproxFunSingularities = "f8fcb915-6b99-5be2-b79a-d6dbef8e6e7e"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowRankApprox = "898213cb-b102-5a47-900c-97e73b919f73"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ApproxFun = "0.11.5"
ApproxFunBase = "0.1.5"
ApproxFunFourier = "0.1.3"
ApproxFunOrthogonalPolynomials = "0.2.2"
ApproxFunSingularities = "0.1.1"
BandedMatrices = "0.9.3, 0.10"
DomainSets = "0.1"
DualNumbers = "0.6"
LowRankApprox = "0.2"
SpecialFunctions = "0.7,0.8"
HypergeometricFunctions = "0.1"
julia = "1"
